---
- name: upgrade packages
  apt: upgrade=yes update_cache=yes
  sudo: true

- name: install common packages
  sudo: yes
  apt: pkg={{ item }} state=present
  tags: [packages]
  with_items:
    - build-essential
    - git
    - fish
    - python-pycurl # Needed for apt_repo
    - fontconfig # Needed for PhantomJS
    - ruby1.9.1

- name: install bundler
  sudo: yes
  gem: name=bundler state=present
