image: bradrydzewski/node:0.10 

script:
  - npm install -g gulp
  - npm install -g pm2
  - npm install -g coffee-script
  - npm install -g mocha
  - npm install -g mocha-phantomjs
  - npm install -g phantomjs
  - npm install -g bower

  - npm install
  - bower install
  - bundle update

  - gulp
  - npm test

services:
  - redis
  - mongodb

notify:
  email:
    recipients:
      - cris.mihalache@spectrumit.eu
