- name: install global npm dependencies
  sudo: yes
  npm: name={{ item }} global=yes
  with_items:
    - gulp
    - pm2
    - coffee-script
    - mocha
    - mocha-phantomjs
    - phantomjs
    - bower

- name: create SSH directory
  file: state=directory path=~/.ssh

- name: upload SSH private key
  copy: src=deploy_key dest=~/.ssh/id_rsa mode=0600

- name: upload SSH public key
  copy: src=deploy_key.pub dest=~/.ssh/id_rsa.pub mode=0600

- name: Install known_hosts file
  copy: src=known_hosts dest=~/.ssh/known_hosts mode=0600

- name: create source directory
  file: state=directory path=/var/adefy mode=0777
  sudo: yes

- name: deploy platform
  git: repo=ssh://git@bitbucket.org/spectrumit/adefyplatform.git dest=/var/adefy version={{ adefy_branch }}

- name: install node dependencies
  command: npm install chdir=/var/adefy

- name: install bower dependencies
  command: bower install --allow-root chdir=/var/adefy

- name: build platform
  command: gulp chdir=/var/adefy

- name: copy admin setup script
  copy: src=setup_admin.js dest=/var/adefy/setup_admin.js

- name: copy adefy user setup script
  copy: src=setup_adefy.js dest=/var/adefy/setup_adefy.js

- name: run admin setup script
  shell: mongo 127.0.0.1:45452 < /var/adefy/setup_admin.js
  ignore_errors: true

- name: run adefy user setup script
  shell: mongo 127.0.0.1:45452 < /var/adefy/setup_adefy.js
  ignore_errors: true

- name: start platform
  shell: 'cd /var/adefy && . /var/adefy/env_vars.sh && NODE_ENV=production pm2 start src/adefy.coffee -i 4'
  register: start_result
  ignore_errors: true

- name: reloading platform
  command: pm2 reload all
  when: start_result|failed
