- name: copy main redis config
  copy: src=main_23521.conf dest=/etc/redis/23521.conf

- name: copy autocomplete redis config
  copy: src=autocomplete_23522.conf dest=/etc/redis/23522.conf

- name: start redis
  service: name=redis-server state=started
