---
domain: app.adefy.com
port: 5000
loglevel: 0
adloglevel: 0
newrelic: true
trafficgen: false

mandrill_apikey: qNnTW7jFhEn40lmizXKDLQ

# The mongo password has to be in the environment
# mongo_pass:
mongo_user: adefy
mongo_host: 127.0.0.1
mongo_port: 45452
mongo_db: adefy

redis_main_db: 3
redis_main_host: 127.0.0.1
redis_main_port: 23521

redis_autocomplete_db: 3
redis_autocomplete_host: 127.0.0.1
redis_autocomplete_port: 23522

stats_host: stats1.adefy.com
stats_port: 8125

# All of the following have to be present on the environment!
#
# paypal_host:
# paypal_client_id:
# paypal_client_secret:
#
# s3_config_accessKeyId:
# s3_config_secretAccessKey:
