---
domain: localhost
port: 5000
loglevel: 0
adloglevel: 0
cron_log_level: 0
newrelic: false

mandrill_apikey: qNnTW7jFhEn40lmizXKDLQ

mongo_user: adefy
mongo_pass: l3xzkDSBhGsAGhGpDWTqOX7NrQWyeNI3CXEfIiyMA2ckKbOn
mongo_host: 127.0.0.1
mongo_port: 45452
mongo_db: adefy_testing

redis_main_db: 0
redis_main_host: 127.0.0.1
redis_main_port: 23521
redis_main_rebuild: false

redis_autocomplete_db: 1
redis_autocomplete_host: 127.0.0.1
redis_autocomplete_port: 23522
redis_autocomplete_rebuild: false

stats_host: stats1.adefy.com
stats_port: 8125

paypal_host: api.sandbox.paypal.com
paypal_client_id: AT_m6RAOQUSm4xMz0HTgvmNWorhhDAqfHyDfxC4KpFEFj-8VGQtNMiLTTt0r
paypal_client_secret: EGDIsBC6DBC1PvmaT6CdQr1AqwDd9EN7EyqFcmLb6ty35VX91PT_A9wXyphT

s3_config_accessKeyId: AKIAIJWEHDVZEFP65Q2Q
s3_config_secretAccessKey: 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
